version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./server/uploads:/app/uploads
    #   - /var/log/iampesmobile:/app/logs
    env_file:
      - ./server/.env

  # frontend:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend