POST http://localhost:5000/api/v1/user/reset-password-callback?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTAxZGRmZjk0N2ZmOTYwYzUzZmJjNzkiLCJmdWxsbmFtZSI6Ik5ndXllbiBIb2FuZyBLaWVuIiwiZW1haWwiOiJraWVubmd1eWVuNDMyMWFiY0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MTczMTEyOSwiZXhwIjoxNzYxNzM0NzI5fQ.hFfuqQ39lSRV3aQYHSsy_bqA1mAEN9Tybb4D9I-pqCs
Content-Type: application/json

{
    "newPassword": "hoangkien321"
}